databases:
  - name: lakeclaireunhoused
    databaseName: lakeclaireunhoused
    user: lakeclaireunhoused

services:
  - type: web
    name: lakeclaireunhoused
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lakeclaireunhoused
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
